---
- name: Install dependencies
  ansible.builtin.include_tasks: install-dependencies.yaml

- name: Disable SWAP
  ansible.builtin.include_tasks: disable-swap.yaml

- name: Install CNI plugins
  ansible.builtin.include_tasks: install-cni-plugins.yaml

- name: Install containerd
  ansible.builtin.include_tasks: install-containerd.yaml

- name: Install kubelet
  ansible.builtin.include_tasks: install-kubelet.yaml

- name: Install kube-proxy
  ansible.builtin.include_tasks: install-kube-proxy.yaml

- name: Install runc
  ansible.builtin.include_tasks: install-runc.yaml

- name: Install crictl
  ansible.builtin.include_tasks: install-crictl.yaml

- name: Reboot the machine
  ansible.builtin.reboot:
    connect_timeout: 30
  become: true
