config/all: config/workers config/controllers

config/workers:
	cd ansible; ansible-playbook -i inventory.ini playbooks/workers.yml

config/controllers:
	cd ansible; ansible-playbook -i inventory.ini playbooks/controllers.yml

config/ping:
	cd ansible; ansible all -m ping -i inventory.ini

config/inventory:
	cd ansible; ansible-inventory -i inventory.ini --list

config/test:
	cd tests; go test -v -run '(TestWorkerConfig|TestControllerConfig)'
