provision/all: provision/workers provision/controllers

provision/workers:
	cd ansible; ansible-playbook -i inventory.ini playbooks/workers.yml

provision/controllers:
	cd ansible; ansible-playbook -i inventory.ini playbooks/controllers.yml

provision/ping:
	cd ansible; ansible all -m ping -i inventory.ini

provision/inventory:
	cd ansible; ansible-inventory -i inventory.ini --list

provision/test:
	cd tests; go test -v -run '(TestWorkerConfig|TestControllerConfig)'
