---
- name: Set a hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"
    use: systemd
  become: true

- name: Get load balancer IP (1/2) - Retrieve IP address
  ansible.builtin.command: "{{ role_path }}/files/get-public-ip.sh"
  delegate_to: 127.0.0.1
  register: public_ip_script_output

- name: Get load balancer IP (2/2) - Set ip as fact
  ansible.builtin.set_fact:
    kubernetes_control_plane_node_load_balancer_ip: "{{ public_ip_script_output.stdout }}"

- name: Mount cgroup filesystem (1/2) - Create systemd service
  ansible.builtin.copy:
    dest: /etc/systemd/system/cgroup-mount.service
    src: cgroup-mount.service
    owner: 'root'
    group: 'root'
    mode: '0644'
  become: true
  notify:
    - Systemd daemon_reload

- name: Mount cgroup filesystem (2/2) - Enable and start systemd service
  systemd:
    name: cgroup-mount
    enabled: yes
    state: started
  become: true
